### ISSUE TITLE
R, Pandas Dataframe?

### ISSUE THREAD

**Issue by douglasArantes** [netzwerg/paleo#24]
This project aims to have features comparable to dataframes of the R language and Pandas library? I have no experience with either, but seem to be very interesting.

I believe that parsing from text is an essential feature, but i think the need to inform the type of each column can be a problem, especially for data sets with tens or hundreds of variables.

In Scala community there are some tools that read and infers the types of the columns of csv files, some tools use Shapeless library for this purpose.

It would be great a robust implementation of dataframe to the JVM ecosystem, as well as in Python and R, although there is already the Apache Spark Dataframe API.

**Comment by netzwerg** [comment]
Thank you for your interest in paleo.

Yes, it would be great to have schema inference!

For starters, it could be a dedicated class in the `ch.netzwerg.paleo.schema` package. The class
should parse the CSV input data and automatically create a `ch.netzwerg.paleo.schema.Schema`. Just
like you mentioned, the actual inference could be similar to what Apache Spark does (see [InferSchema.scala](https://github.com/databricks/spark-csv/blob/cbc72fe8fbd414f9e732714abdf9388e8cea7e40/src/main/scala/com/databricks/spark/csv/util/InferSchema.scala)).

Would you be willing to write a PR?

**Comment by douglasArantes** [comment]
I still do not know how to make a good implementation, but I will study some approaches. The implementation need to be made in Java? I believe some Scala libraries facilitate implementation.

**Comment by netzwerg** [comment]
Excellent! The paleo parser is implemented in Scala, so you are free to use Scala as long as the public API is in Java. I would like to keep paleo's dependencies minimal, therefore a solution which doesn't involve any additional libraries would be preferable.

On another note: If you are able to use Scala in your project, maybe one of the existing Scala data frame libraries already solves your needs? Most of them are way more advanced than paleo. [This blog post](https://darrenjw.wordpress.com/2015/08/21/data-frames-and-tables-in-scala/) presents a nice overview/comparison.

**Comment by douglasArantes** [comment]
I will test the libraries mentioned in the blog.

Thank's.
