### ISSUE TITLE
IDEA can't import Gradle project without $BINTRAY_USER

### ISSUE THREAD

**Issue by chronodm** [netzwerg/paleo#25]
Steps to reproduce:

1. Fork the repository.
2. In IDEA, select **File / New project from existing sources*.
3. Select `paleo/build.gradle`.
4. Accept default options.

Expected:

- Project imports.

Actual:

- Import fails in **Gradle: Configure Projects** with **Resolve Error: Could not find property 'BINTRAY_USER' on com.jfrog.bintray.gradle.BintrayExtension_Decorated @ 623e15a2**

<img width="527" alt="screen shot 2016-04-17 at 3 18 35 pm" src="https://cloud.githubusercontent.com/assets/2934647/14590456/c9738aec-04af-11e6-920c-83f8958b9b49.png">

Notes:

- See attached [stacktrace](https://github.com/netzwerg/paleo/files/222884/stacktrace.txt).

**Comment by netzwerg** [comment]
Thanks, David!

**Comment by netzwerg** [comment]
Just a heads-up regarding another import issue with the latest IDEA 2016.1 EAP: #27

**Comment by dmolesUC3** [comment]
No problem!
