### ISSUE TITLE
Add isEmpty and isNotEmpty methods to Column and AbstractColumn 

### ISSUE THREAD

**Issue by RobWin** [netzwerg/paleo#33]
What do you think about adding an `isEmpty` and `isNotEmpty` method to the `Column` interface?

`DateFrame.of` could check that a column is not empty an add the column only when the column is not empty?

Background: I have to build a table (in [Swagger2Markup](https://github.com/Swagger2Markup/swagger2markup)), but I don't want to add columns which are empty. I can't check upfront if the column will be empty.

**Comment by netzwerg** [comment]
Conceptually, there's no reason why a `DataFrame` should not be empty, there's even a `DataFrame.empty()` factory method. So `isEmpty` on the `Column` interface would just be more convenient than `getRowCount() == 0`, right?

**Comment by RobWin** [comment]
Sry I meant DataFrame.allOf could check of a column is empty. Otherwise I would need a DaraFrame.Builder()

**Comment by netzwerg** [comment]
Hmm, I am not sure whether I am following: From paleo's perspective, adding empty columns is perfectly fine. If you have a use case where that should be disallowed, couldn't you check it before calling `DataFrame.ofAll(...)`?

**Comment by RobWin** [comment]
I describe my issue better tomorrow. I only have an iPhone atm.
I think I only need an isBlank method in StringColumn or I have to use a predicate by my own.

**Comment by RobWin** [comment]
Yes, you are right. It doesn't make sense to change DataFrame.allOf.
I'm going to build some utility functions.

**Comment by RobWin** [comment]
Just for your information. I use paleo-core in Swagger2Markup now.

I just wrote a wrapper around it:

```
public static Table ofAll(StringColumn... columns) {
   return new Table(DataFrame.ofAll(List.of(columns).filter(Table::isNotBlank)));
}

public static boolean isNotBlank(StringColumn column) {
   return !column.getValues().filter(StringUtils::isNotBlank).isEmpty();
}
```

**Comment by netzwerg** [comment]
Excellent, thanks for letting me know!
